Repository jenkins-x-plugins/jx-preview, pull requests merged in 2020-11, with the labels that each got.

#113 fix: create jx-values for preview-gc-jobs
  pkg/cmd/destroy/destroy.go
Labels: approved, ok-to-test, size/L

#114 fix: add support for jx-values.yaml create in destroy
  go.mod
  go.sum
  pkg/cmd/create/create.go
  pkg/cmd/create/create_test.go
  pkg/cmd/create/test_data/sample_project/charts/someapp/Chart.yaml
  pkg/cmd/create/test_data/sample_project/preview/.gitignore
  pkg/cmd/create/test_data/sample_project/preview/helmfile.yaml
  pkg/cmd/create/test_data/sample_project/preview/values.yaml.gotmpl
  pkg/cmd/destroy/destroy.go
  pkg/cmd/gc/gc.go
  pkg/cmd/gc/test_data/myorg/my-gitops-repo/jx-values.yaml
  pkg/cmd/gc/test_data/myorg/my-gitops-repo/master/jx-values.yaml
  pkg/previews/discover_helmfile.go
  pkg/previews/jx_values.go
Labels: approved, size/L

#116 fix: switch to a fix for preview gc
  go.mod
  go.sum
  pkg/cmd/create/create_test.go
  pkg/previews/jx_values.go
Labels: approved, size/M

#117 fix: lets log a warning if the helmfile destroy fails
  go.mod
  go.sum
  pkg/cmd/destroy/destroy.go
Labels: approved, size/M

#124 fix: lets capture the author details
  pkg/cmd/create/create.go
Labels: approved, size/S

#126 fix: fix no chart found errors when adding charts from a helm repository
  pkg/cmd/create/create.go
  pkg/cmd/create/create_test.go
Labels: approved, size/S

#127 fix: add multi-arch image
  .goreleaser.yml
  .lighthouse/jenkins-x/Kptfile
  .lighthouse/jenkins-x/pullrequest.yaml
  .lighthouse/jenkins-x/release.yaml
  .lighthouse/jenkins-x/triggers.yaml
  Dockerfile
  build.sh
  cloudbuild.yaml
  go.mod
  go.sum
Labels: approved, size/XL

#130 fix: multi arch pipeline
  .lighthouse/jenkins-x/release.yaml
  Dockerfile
Labels: approved

#131 fix: improve image to avoid downloading plugin each time
  .lighthouse/jenkins-x/pullrequest.yaml
  Dockerfile
  Dockerfile-preview
  charts/jx-preview/templates/gc-jobs-cj.yaml
  charts/jx-preview/values.yaml
Labels: approved, size/M
