Repository jenkins-x-plugins/jx-preview, pull requests merged in 2020-12, with the labels that each got.

#138 fix: add optional knative serve support for discovering preview URLs
  go.mod
  go.sum
  hack/changelog-header.md
  pkg/cmd/create/create.go
  pkg/cmd/create/create_test.go
  pkg/kserving/constants.go
  pkg/kserving/kservices.go
Labels: approved, lgtm, size/XL

#141 fix: Try fixing the failing ksvc url
  pkg/cmd/create/create.go
Labels: approved, lgtm, ok-to-test, size/XS

#144 Not finding a URL should not be an error
  pkg/cmd/create/create.go
Labels: approved, lgtm, ok-to-test, size/XS

#145 fix: use the right plugin version in the image
  Dockerfile
Labels: approved, size/XS

#142 refactor: remove old v2 requirements
  .gitignore
  go.mod
  go.sum
  pkg/cmd/create/create.go
  pkg/cmd/create/create_test.go
  pkg/cmd/destroy/destroy.go
  pkg/cmd/gc/gc_test.go
  pkg/cmd/get/get.go
  pkg/previews/jx_values.go
Labels: approved, size/M

#148 refactor: move traditional CRDs back to jenkins.io group so we dont need to create new CRDs
  go.mod
  go.sum
  pkg/cmd/create/create.go
  pkg/cmd/create/create_test.go
  pkg/cmd/get/get.go
Labels: approved, size/S

#150 chore: upgrade pipelines
  .lighthouse/jenkins-x/Kptfile
  .lighthouse/jenkins-x/pullrequest.yaml
  .lighthouse/jenkins-x/release.yaml
Labels: size/M, updatebot

#154 fix: migrate to multiarch pack
  .lighthouse/jenkins-x/Kptfile
  .lighthouse/jenkins-x/pullrequest.yaml
  .lighthouse/jenkins-x/release.yaml
Labels: approved, size/M

#157 fix: use the new location of jx-values.yaml
  go.mod
  go.sum
  pkg/cmd/create/test_data/myorg/my-gitops-repo/helmfiles/jx/jx-values.yaml
  pkg/cmd/gc/test_data/myorg/my-gitops-repo/helmfiles/jx/jx-values.yaml
  pkg/cmd/gc/test_data/myorg/my-gitops-repo/master/helmfiles/jx/jx-values.yaml
  pkg/previews/jx_values.go
Labels: approved, size/M

#158 fix: remove the old image pull secret file
  pkg/cmd/create/create.go
Labels: approved, size/S

#162 fix(lighthouse): inverse steps order so the correct version and value are used in 'release-chart' step.
  .lighthouse/jenkins-x/release.yaml
Labels: needs-ok-to-test, size/S

#173 chore: upgrade deps
  go.mod
  go.sum
Labels: approved, size/S

#183 fix: upgrade deps
  go.mod
  go.sum
  pkg/cmd/create/create.go
Labels: approved, size/M
