Repository jenkins-x-plugins/jx-preview, pull requests merged in 2021-04, with the labels that each got.

#328 chore: upgrade deps
  go.mod
  go.sum
Labels: approved, size/M

#330 fix: allow optional path added to the preview URL
  docs/cmd/jx-preview.md
  docs/cmd/jx-preview_create.md
  docs/cmd/jx-preview_destroy.md
  docs/cmd/jx-preview_gc.md
  docs/cmd/jx-preview_get.md
  docs/cmd/jx-preview_version.md
  docs/crds/github-com-jenkins-x-plugins-jx-preview-pkg-apis-preview-v1alpha1.md
  docs/man/man1/jx-preview-create.1
  docs/man/man1/jx-preview-destroy.1
  go.mod
  go.sum
  pkg/cmd/create/create.go
  pkg/cmd/create/create_test.go
  pkg/cmd/destroy/destroy.go
  pkg/cmd/gc/gc.go
  pkg/cmd/gc/gc_test.go
  pkg/cmd/get/get.go
  pkg/cmd/root.go
  pkg/kserving/kservices.go
  pkg/previews/clients.go
  pkg/previews/fakepreviews/helpers.go
  pkg/previews/jx_values.go
  pkg/previews/previews.go
Labels: approved, size/L

#331 fix: support other git provider
  charts/jx-preview/templates/gc-jobs-cj.yaml
  charts/jx-preview/values.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#332 fix: value error
  charts/jx-preview/templates/gc-jobs-cj.yaml
  charts/jx-preview/values.yaml
Labels: approved, lgtm, ok-to-test, size/S

#333 fix: added JSON schema generation
  Makefile
  cmd/schemagen/main.go
  go.mod
  go.sum
  schema/preview.jenkins.io/v1alpha1/preview.json
Labels: approved, size/L

#334 fix: upgrade the boot image
  Dockerfile
Labels: approved, size/XS
