Repository jenkins-x-plugins/jx-preview, pull requests merged in 2021-01, with the labels that each got.

#196 feat: allow user to specify pod annotations for gc job
  charts/jx-preview/templates/gc-jobs-cj.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#208 fix: upgrade base image
  Dockerfile
Labels: approved, size/XS

#226 chore: upgrade go dependencies
  go.mod
  go.sum
Labels: size/M, updatebot

#228 chore: upgrade go dependencies
  go.mod
  go.sum
Labels: size/XS, updatebot

#229 chore: upgrade go dependencies
  go.mod
  go.sum
Labels: updatebot

#234 fix: add selection of preview to remove
  .lighthouse/jenkins-x/release.yaml
  go.mod
  go.sum
  pkg/cmd/destroy/destroy.go
Labels: size/XL

#171 docs: how to debug jx preview inside a pipeline step
  README.md
Labels: needs-ok-to-test, size/M

#244 chore: upgrade pipelines
  .lighthouse/jenkins-x/Kptfile
  .lighthouse/jenkins-x/pullrequest.yaml
  .lighthouse/jenkins-x/release.yaml
Labels: size/L, updatebot

#247 fix: upgrade base image
  Dockerfile
Labels: approved, size/XS

#248 chore: upgrade deps
  go.mod
  go.sum
Labels: approved, size/M

#249 chore: upgrade deps
  go.mod
  go.sum
Labels: approved, size/S

#250 fix: set XDG_CONFIG_HOME
  charts/jx-preview/templates/gc-jobs-cj.yaml
Labels: approved, lgtm, ok-to-test, size/XS
