Repository jenkins-x-plugins/jx-preview, pull requests merged in 2021-03, with the labels that each got.

#282 fix: release the preview chart
  .github/workflows/jenkins-x-release.yaml
  .github/workflows/jenkins-x/release-chart.sh
Labels: approved, size/S

#283 fix: release the preview chart
  .github/workflows/jenkins-x/release-chart.sh
Labels: approved, size/XS

#284 fix: release the preview chart
  .github/workflows/jenkins-x-release.yaml
Labels: approved, size/XS

#285 fix: add secret so we can publish to gcs
  .github/workflows/jenkins-x-release.yaml
Labels: approved, size/XS

#286 fix: use github pages for chart
  .github/.jx/settings.yaml
  .github/workflows/jenkins-x-release.yaml
  .github/workflows/jenkins-x/release-chart.sh
Labels: approved, size/S

#287 fix: use github pages for chart
  .jx/settings.yaml
Labels: approved, size/XS

#292 fix: switch to the github image
  charts/jx-preview/values.yaml
  go.mod
  go.sum
Labels: approved, size/S

#304 fix: avoid the go-scm for fetching the jx-values.yaml file
  go.mod
  go.sum
  pkg/cmd/create/create.go
  pkg/cmd/create/create_test.go
  pkg/cmd/destroy/destroy.go
  pkg/previews/jx_values.go
Labels: approved, size/L

#306 chore: fix CI tests
  pkg/cmd/create/create_test.go
Labels: approved, size/XS

#307 chore: fix CI tests
  pkg/cmd/create/create_test.go
  pkg/cmd/gc/gc_test.go
Labels: approved, size/XS

#310 fix: upgrade deps
  go.mod
  go.sum
Labels: approved, size/S

#315 fix: the docker registry
  .jx/settings.yaml
  .lighthouse/jenkins-x/pullrequest.yaml
  go.mod
  go.sum
Labels: approved, size/S

#321 chore: upgrade deps
  go.mod
  go.sum
Labels: approved, size/S

#327 chore: move to plugins org
  .jx/updatebot.yaml
  Makefile
  README.md
  charts/jx-preview/Chart.yaml
  charts/jx-preview/values.yaml
  cmd/app/main-win.go
  cmd/app/main.go
  cmd/docs/main.go
  cmd/main.go
  docs/crds/github-com-jenkins-x-jx-preview-pkg-apis-preview-v1alpha1.md
  go.mod
  go.sum
  hack/changelog-header.md
  hack/update-codegen.sh
  pkg/apis/preview/v1alpha1/doc.go
  pkg/apis/preview/v1alpha1/register.go
  pkg/client/clientset/versioned/clientset.go
  pkg/client/clientset/versioned/fake/clientset_generated.go
  pkg/client/clientset/versioned/fake/register.go
  pkg/client/clientset/versioned/scheme/register.go
  pkg/client/clientset/versioned/typed/preview/v1alpha1/fake/fake_preview.go
  pkg/client/clientset/versioned/typed/preview/v1alpha1/fake/fake_preview_client.go
  pkg/client/clientset/versioned/typed/preview/v1alpha1/preview.go
  pkg/client/clientset/versioned/typed/preview/v1alpha1/preview_client.go
  pkg/client/informers/externalversions/factory.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/informers/externalversions/internalinterfaces/factory_interfaces.go
  pkg/client/informers/externalversions/preview/interface.go
  pkg/client/informers/externalversions/preview/v1alpha1/interface.go
  pkg/client/informers/externalversions/preview/v1alpha1/preview.go
  pkg/client/listers/preview/v1alpha1/preview.go
  pkg/cmd/create/create.go
  pkg/cmd/create/create_test.go
  pkg/cmd/destroy/destroy.go
  pkg/cmd/gc/gc.go
  pkg/cmd/gc/gc_test.go
  pkg/cmd/get/get.go
  pkg/cmd/root.go
  pkg/previews/clients.go
  pkg/previews/fakepreviews/helpers.go
  pkg/previews/previews.go
  pkg/previews/sort.go
Labels: approved
