Repository jenkins-x-plugins/jx-preview, pull requests merged in 2022-09, with the labels that each got.

#379 chore: Cleanup and upgrade
  OWNERS
  OWNERS_ALIASES
  go.mod
  go.sum
  pkg/cmd/create/create.go
  pkg/cmd/destroy/destroy.go
  pkg/cmd/template/template.go
  pkg/previews/discover_helmfile.go
  pkg/previews/jx_values.go
Labels: size/L, approved

#383 chore: specify an optional preview destroy dir parameter
  pkg/cmd/destroy/destroy.go
Labels: approved, size/S, ok-to-test

#384 fix: upgraded jx-gitops to 0.8.2
  go.mod
  go.sum
Labels: approved, size/S

#382 feat: add supply chain security
  .github/workflows/jenkins-x-release.yaml
  .github/workflows/jenkins-x/sbom-container.sh
  .github/workflows/jenkins-x/upload-binaries.sh
  .gitignore
  .goreleaser.yml
Labels: size/M, approved, lgtm, ok-to-test

#387 refactor: upgrade go version to 1.18
  Makefile
  go.mod
  go.sum
Labels: size/L, approved
